### ISSUE TITLE
出现了错误，请您帮一下忙，感谢

### ISSUE THREAD

**Issue by ddll2333** [eeorunix/girls-frontline-helper#1]
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    ko.solve()
  File "C:\Users\86130\Downloads\girls-frontline-helper-master\src\N_0_1.py", line 78, in solve
    index = self.detach()
  File "C:\Users\86130\Downloads\girls-frontline-helper-master\src\N_0_1.py", line 15, in detach
    self.get_pic()
  File "C:\Users\86130\Downloads\girls-frontline-helper-master\src\template.py", line 54, in get_pic
    save_bit_map.SaveBitmapFile(save_dc, self.filename)
win32ui.error: CreateFile

出现了这几个错误，我不是懂这是怎么回事，请您帮帮忙谢谢，我的邮箱：2825330393@qq.com

**Comment by eeorunix** [comment]
@ddll2333 你还玩这游戏嘛，玩的话我就更新一下

**Comment by Meilokis** [comment]
蛤蛤 玩

**Comment by eeorunix** [comment]
@ddll2333 @Meilokis 已经更新完了
